# Site settings
title: "Jaeyong Hwang Resume"
description: "Jaeyong Hwang Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jaeyong Hwang"
resume_title:                   "<b>About me</b>"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "wo7516@kaist.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

#resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"
resume_header_intro: "Undergraduate student, Physics<br><b>Korea Advanced Institute of Science and Technology (KAIST)</b><br><br><b>Research Interests</b> <ul class=\"resume-item-list\"><li>Constructing qubit system via superconductor-based or Rydberg atom array cavity</li><li>Implementation of Quantum Algorithm</li><li>Quantum Machine Learning</li></ul> e-mail: wo7516 at kaist.ac.kr<br>Check out CV here"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_awards:          true
resume_section_publications:    true
resume_section_presentations:   true
resume_section_patents:         true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_activities:      true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/itsjaeyong"
  #resume_twitter_url:           "https://github.com/itsjaeyong"
  #resume_dribbble_url:          "https://github.com/itsjaeyong"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://github.com/itsjaeyong"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "https://github.com/itsjaeyong"
  #resume_medium_url:            "https://github.com/itsjaeyong"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
